---
#########################
#########################
## Golang Linter rules ##
#########################
#########################

# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  timeout: 10m
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
  new: true
linters:
  enable:
    - gosec
    - unconvert
    - goconst
    - goimports
    - gofmt
    - gocritic
    - govet
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
linters-settings:
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
  govet:
    # report about shadowed variables
    check-shadowing: false
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  gocritic:
    disabled-checks:
      - singleCaseSwitch
      - appendAssign
  revive:
    ignore-generated-header: true
    severity: warning
