name: Go

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  go:
    uses: openconfig/common-ci/.github/workflows/go.yml@88a41b190576ebf6d51b5204c1056af2bda19036
    permissions:
      contents: read
      packages: read
      # To report Github Actions status checks
      statuses: write

  linter:
    uses: openconfig/common-ci/.github/workflows/linter.yml@9bd215b60afdefd1633ca8d20101cd03534e19b1
    permissions:
      contents: read
      packages: read
      # To report Github Actions status checks
      statuses: write
