name: Go

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  go:
    uses: openconfig/common-ci/.github/workflows/go.yml@2dd20d500dc65de2927c44877398fdd141ee09ba

  linter:
    uses: openconfig/common-ci/.github/workflows/linter.yml@2dd20d500dc65de2927c44877398fdd141ee09ba
