name: Go

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  go:
    uses: openconfig/common-ci/.github/workflows/go.yml@6471e41fc17c67b8fb10f99b91bbb4ba5903effc

  linter:
    uses: openconfig/common-ci/.github/workflows/linter.yml@6471e41fc17c67b8fb10f99b91bbb4ba5903effc
